INSERT INTO media (title, authorCreator, genre, rating, media_type, checkedOut)
    VALUES("Harry Potter and the Sorcerer's Stone", "J.K. Rowling", "Fantasty", "Young Adult", "Book", false),
            ("The Hunger Games (The Hunger Games, #1)", "Suzanne Collins", "Science Fiction", "Young Adult", "Book", false),
            ("Fifty Shades of Grey", "E.L. James", "Romance", "Adult", "Book", false),
            ("Pride & Prejudice", "Jane Austen", "Romance", "Adult", "Book", false),
            ("The Eye of the World (The Wheel of Time, #1)", "Robert Jordan", "Fantasy", "Adult", "Book", false),
            ("The Final Empire (Mistborn, #1)", "Brandon Sanderson", "Fantasy", "Young Adult", "Book", false),
            ("In Bruges", "Martin McDonagh", "Comedy", "R", "Movie", false),
            ("The Grand Budapest Hotel", "Wes Anderson", "Adventure", "R", "Movie", false),
            ("The Hunt for Red October", "John McTiernan", "Action", "PG", "Movie", false),
            ("Stargate SG-1", "Jonathan Glassner & Brad Wright", "Sci-Fi", "TV-14", "TV-Show", false),
            ("Sex Education", "Laurie Nunn", "Comedy", "TV-MA", "TV-Show", false),
            ("I Am Not Okay with This", "Jonathan Entwistle & Christy Hall", "Comedy", "TV-MA", "TV-Show", false),
            ("Avatar: The Last Airbender", "Michael Dante DiMartino & Bryan Konietzko", "Animation", "TV-Y7-FV", "TV-Show", false),
            ("Awesomenauts", "Ronimo Games", "MOBA", "T", "Video Game", false),
            ("Terraria", "Re-Logic", "Action-adventure game", "T", "Video Game", false),
            ("The Witcher", "CD Projekt", "Action role-playing","M", "Video Game",false);
